name: Deploy Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: cathe-org/actions/.github/workflows/deploy/website.yml@main
    with:
      site_directory: /var/www/jpears.me
    secrets: inherit